### ISSUE TITLE
Saving Temperature Data to txt file

### ISSUE THREAD

**Issue by hayatonakamura** [abood91/RPiMLX90640#3]
Thank you for the great repository!

I am attempting to run this on the raspberry pi and saving the temperature values (Celsius) on a txt file  I am having trouble modifying the code so that it will accurately save temperature data. Also, it does not seem to be saving image files in /img/... 
Thanks in advance!

**Comment by abood91** [comment]
Hi @hayatonakamura  could you please share some code so i can check this with you ? 

in the img folder you should see ddmmyy.temp.txt where ddmmyy is the date time that this image was taken, in the same folder you will also see ddmmyy.rgb.txt where rgb.txt is the image only rgb values of each pixel is saved as text

**Comment by hayatonakamura** [comment]
Hi,

Thank you for the reply. I attempt to store the readings of the sensor by modifying your function below. I hope this helps.

```
array2d* NormaliseValue()
{
  double returnValues[NROWS][NCOLS];
  //return (double)(Value - MINTEMP) / (double)(MAXTEMP - MINTEMP);

  for (i=0; i<NROWS; i++) {
      for (j=0; j<NCOLS; j++) {
        returnValues[i][j] = (double)(IMA[i][j] - MINTEMP) / (double)(MAXTEMP - MINTEMP);
      }
  }

ofstream datafile;
datafile.open("data.txt", fstream::app);

  for (i=0; i<NROWS; i++) {
      //pc.printf("D%2d:",i);
      for (j=0; j<NCOLS; j++) {
        printf("%5.3f;", returnValues[i][j]);
	datafile << IMA[i][j] << " ";
      }
 printf("\n\r");
datafile << "\n";
  }
	datafile << "\n";
	datafile.close();
  return &returnValues;

}
```

**Comment by abood91** [comment]
HI @hayatonakamura  Is this still an issue ?
