### ISSUE TITLE
compatibility with smbus on python?

### ISSUE THREAD

**Issue by dcomins** [abood91/RPiMLX90640#5]
Hi abood,

I'am using your MLX90640 driver in order to obtain the temperature matrix in my script on python. After that I use the smbus library to obtain a sensor data but my script get stucked. There is some incompatability between your bcm_2835 i2c driver and smbus? How could I solve my issue?

Regards,

Diego Comin

**Comment by abood91** [comment]
Hello @dcomins  Can you please share your code that get stuck, particularly the i2c code ?

**Comment by dcomins** [comment]
Hello, the main problem with your library is that when I execute sudo ./MLX90640 10 and after I cancel the executable with Ctrl+C I put the command i2cdetect -y 1 in order to see the I2C address from the others sensors and I am not able to detect them, actually I detect no address. 
So from my script in python I modified your library to obtain a .so file and I am able with a extern "C" and ctypes library from python to access to a C++ function modified in your library to obtain the matrix of temperature data, so I am able to obtain the matrix of temp data in python but after this, when I want to read another sensor the error that outputs is that the i2c address I put dont exists, and my python script stop working. 

I attach here my screens:

![image](https://user-images.githubusercontent.com/20353282/51247981-fd771100-198e-11e9-8ab9-273a8a53c4d6.png)


![image](https://user-images.githubusercontent.com/20353282/51247811-83df2300-198e-11e9-8339-d0a3820fad5f.png)

**Comment by abood91** [comment]
HI @dcomins 

I think i have found the issue, 

in main.cpp the i2c is opened but never closed 

try adding `bcm2835_i2c_end();` before the end of the main function.

Or you can just pull the new code as i have added that line
