### ISSUE TITLE
The temperature value obtained is raw value?

### ISSUE THREAD

**Issue by koks123456** [abood91/RPiMLX90640#6]
Hi, is the temperature value obtained is the raw value? Does it show for each pixel? and how to convert into degree celsius? thank you

**Comment by abood91** [comment]
Hi @koks123456  please refer to this https://github.com/abood91/RPiMLX90640/issues/3 
as the issue tells you there is already that code that saves the raw data (temperature values pixel by pixel )
its in https://github.com/abood91/RPiMLX90640/blob/master/main.cpp line 427 - 453

**Comment by koks123456** [comment]
can ask how to show temperature value in degree celsius?

**Comment by abood91** [comment]
they are already saved in degree Celsius, if you open the file i mentioned /img/ddmmyyy.temp.txt you will see that the data in degree Celsius,  you only need to device that number by 10 in order to get it in float

**Comment by koks123456** [comment]
thank you for your reply. But l didn't see any /img/ddmmyyy.temp.txt in my folder, does it will be created after l run this program? Can you show the output when you run your program? because l get some weird values....When l run cpp file separately such as l run sensor.cpp alone, it shows error. what should l need to do ? thank you

**Comment by abood91** [comment]
Hi!
First of all , run the main.cpp 
as for the output you do need to create that folder and check if that line of code is enabled.
also some logs would be good
